apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: jenkins/jnlp-slave:4.6-1
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker
  - name: docker
    command:
    - cat
    env:
    - name: JENKINS_TUNNEL
      value: jenkins-agent:50000
    image: library/docker:19.03.7
    tty: true
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker
    resources:
      limits:
        cpu: 2
        memory: 2Gi
      requests:
        cpu: 1
        memory: 2Gi
  volumes:
  - hostPath:
      path: /var/run/docker.sock
    name: docker
